[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SANITY_DATASET,VITE_TELEGRAM_BOT_TOKEN,VITE_TELEGRAM_CHAT_ID,VITE_TELEGRAM_CHAT_ID_2,VITE_FB_PAGE_ID,VITE_YT_CHANNEL_ID,VITE_SANITY_PROJECT_ID,VITE_FB_ACCESS_TOKEN,VITE_YT_API_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200